apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: resource-reader
rules:
- apiGroups: [""]
  resources: ["secrets", "pods", "configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-sa-binding
subjects:
- kind: ServiceAccount
  name: app-sa
  namespace: default
roleRef:
  kind: Role
  name: resource-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: user1-secret
data:
  username: dXNlcjEK
  password: cGFzc3dvcmQx
---
apiVersion: v1
kind: Secret
metadata:
  name: user2-secret
data:
  username: dXNlcjIK
  password: cGFzc3dvcmQy
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-privileged
spec:
  hostPID: true
  serviceAccountName: app-sa
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: [ "sleep", "infinity" ]
    securityContext:
      privileged: true
    volumeMounts:
    - name: secret-vol
      mountPath: "/etc/secret"
      readOnly: true
  volumes:
  - name: secret-vol
    secret:
      secretName: user1-secret
