apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: "only-clusterip-access"
  namespace: unguard
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: proxy-service
      app.kubernetes.io/part-of: unguard
  kprobes:
  - call: "tcp_connect"
    message: "Only allow connections to ClusterIP services"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchArgs:
      - index: 0
        operator: "NotDAddr"
        values:
        - 127.0.0.1
        - "10.0.0.0/8" # podCIDR
        - "10.96.0.0/12" # serviceCIDR
      matchActions:
      - action: Sigkill
